Takeda-Takumi/Timetable

README.md

Add ling to README.md

---

README.md

add into README.md

---

subject.py

subject.pyにクラスSubjectとクラスAssignmentを記載しました
Closes #18

[add] クラスSubjectとAssignmentの追加

---

README.md

kivyを使うのをやめたので、kivyのリンクを削除しました

[remove] READMEのkivy関連の項目の削除

---

main.py

detail_windowが閉じるときに実行する用の関数dw_close()を追加し、テキストと色を変更する関数をupdate関数から分離させてdw_close()から実行できるようにしました。

[update] Applicationにdw_close()関数を追加

---

detail_window.py

[fix]show_window
tk.BooleanVarによってウィンドウの削除を検知できるように変更
[add]set_func
[add]del_func
詳細ウィンドウ内における各タイミングのイベント関数を設定できるように追加
詳細なリファレンスはコード内ドキュメントを参照
リファレンス追加:
コード内にDetailWindowに関するリファレンスを追加
コード内かpydocコマンドによって参照可能

[add] show_windowの仕様変更とイベント設定機能の追加

---

main.py
widget.py

main.py detail_window.pyの仕様に適用させました。
widget.py set_button_func()の仕様をdetail_window.pyのset_func()の仕様に寄せました。

[update] main.pyとwidget.pyの関数受け渡し方法を変更

---

detail_window.py

[add]GuideEntry
ガイドテキスト付きのEntryを表すクラスGuideEntryを追加
当クラスはdetail_window.py以外のスクリプトでも利用可能
リファレンスはコート内かpydocを参照
[update] DetailWindow
GuideEntryの実装に伴い、詳細ウィンドウの一部EntryをGuideEntryに置き換えた

[add] class GuideEntryの追加

---

main.py

__init__にテストデータの入力やカレンダーの作成などがたくさん書いてあったため、可読性を上げるためにそれぞれの用途ごとにメソッドかしました。
create_teimtable() : カレンダー本体を表示するメソッド
input_test_data() : テストデータを入力するメソッド

[clean] main.pyの__init__メソッドの整理

---

detail_window.py

[update]DetailWidnow
ウィンドウを破棄、再展開しても以前の展開位置を保存するように仕様変更
[add]set_pos
ウィンドウの展開位置を設定するset_pos関数をDetailWindowに追加

[add & update] DetailWindowに位置保存機能を追加

---

detail_window.py

課題追加ボタンを押すと、課題目と期限を選択するWindowを作成しました。
課題名入力で、マウスをクリックするとデフォルトの課題名が消え、入力できる機能の追加しました。
キーボード入力の代わりに、comboboxで提出期限日付や時間の選択機能を追加しました。

Feature/add InputAssignment

---

detail_window.py

変数の統一と修正date->day, second->minute
デフォルトの日付（2022/01/01)を現在の日付にする機能を追加しました。
デフォルトの課題名を灰色にし、入力された後は黒に代わる機能を追加しました。
OKボタンをAddに修正、マウスを近づけると赤になるように修正しました。
入力からの日付をstr型ー＞intに変更しました。
>

<[fix&update]日付の取得と入力UIの修正

---

detail_window.py
input_assignment.py
subject.py

[update] DetailWindow
DetailWindowへInputAssignmentを用いた課題追加機能を追加
(ただし、現在未完成)
[add & update] InputAssignment
イベント設定機能追加
一部メンバ関数の仕様を変更
メンバ関数を追加
また、定義をinput_assignment.pyに移行
[add & update] Assignment
__init__関数の仕様を変更(既存の利用に影響なし)
__str__関数を追加
[update] Subject
add_asg関数の引数を変更

[add & update] DetailWindowへ課題追加機能の追加(未完成)

---

subject.py

[update] Subject
main.pyとの整合性をとるため、add_asg関数を修正した

[update] Subject.add_asgの修正

---

widget.py

set_subject() : 引数で指定されたSubject型のオブジェクトをself._subjectに設定するメソッド
また、テストを行うために if __name__ も追加した

[add] widget.pyにsubject型をそのまま保存できるメソッドを追加した

---

.gitignore
main.py

詳細ウィンドウ側で更新された科目名や課題内容などを別ファイルで保存できるようにしました。
保存を行うと、
timetable.shelve.bak
timetable.shelve.dat
timetable.shelve.dir
が作成されます。
save_timetable() : 時間割を保存する
load_timetalbe() : 時間割を読み込む

[add] データ保存機能の追加

---

custom_widgets.py
detail_window.py

[add] AssignmentFrame
Assignmentを詳細ウィンドウを表示する用のクラスAssignmentFrameを追加
DetailWindow内部での利用のみを想定
[update] ScrollFrame
AssignmentFrame実装に伴い、一部の関数の仕様を変更

[add] 課題表示用のレイアウトウィジェットを追加

---

main.py

main.pyの頭に, 定数として文字型の変数
BASE_COLOR
ACCENT_COLOR
の2つを追加しました

[add] ベースカラーとアクセントカラーの追加

---

detail_window.py

課題追加フォームで存在しない日付を指定できてしまうバグの修正＆閏年の追加を行いました。
comboboxを読み込み専用（修正不可）に変更しました。
ベースカラーとアクセントカラーの統一＆変数追加を行いました。

[fix&upadte]課題追加フォームで存在しない日付を指定できてしまうバグの修正＆閏年の追加

---

main.py
widget.py

mainとwidgetそれぞれに
BASE_COLOR = "#F9F9F9"
ACCENT_COLOR = "#00ACEE"
という定数を導入した
また、このベースカラーをカレンダーに反映させた

[add] mainとwidgetにベースカラーとアクセントカラーを追加し、反映する

---

input_assignment.py

カラー統一のため、
_base_color、_accent_colorの変数を追加しました。

[add] input_assignmentにbase色とaccent色の追加

---

main.py
widget.py

科目名などが見切れないように、１コマのサイズを大きくしました。
また、起動時のウィンドウの比率に応じて、コマの大きさを変えるようにしました。

[update] カレンダー1コマのサイズを変更

---

custom_widgets.py
detail_window.py

[add] DetailWindow
削除ボタンによる課題の削除機能を追加
[update] ScrollFrame
削除機能実装にともない、メンバ関数の追加

[add] 課題の削除機能の追加

---

widget.py

追加した関数
enter_widget : マウスオーバーした際に呼び出される関数
leave_widget : マウスがwidgetから離れた際に呼び出される関数

[add] マウスオーバーした際にwidgetの色を濃くする

---

input_assignment.py

デフォルトの課題名入力を変更しました。
課題名を入力した際に、アクセント色が変わるように修正しました。

[update]input_assignmentの課題入力欄の修正

---

input_assignment.py

期限の過ぎた課題を追加する際に
「既に期限が過ぎています！
n時間前の課題です！」とエラーウィンドウを出力する機能を付けました。
入力日付と現在時刻との比較関数checkdeadline()を追加しました。

[add] 期限の過ぎた課題を追加する際にエラーウィンドウの出力機能追加

---

detail_window.py

[update] Detail_window
最近の締め切りを更新する機能の追加

[update] 最近の締め切り更新機能の追加

---

main.py

main.pyの要らないコメントやスペースなどを削除しました

[clean] main.pyの整理

---

custom_widgets.py
detail_window.py

custom_widgets&detail_window
リリース用に不要なコードを削除した

[clean] 不要なコードの削除

---

input_assignment.py

input_assignmentコードの整理をしました。
必要のないコードを削除しました。

[clean]input_assignmentコードの整理
